### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by jingfengguo-ai** [longxiang-ai/Human101#1]
It's a very impressive work which really attracts me.
I wonder when will the code be released as I have academic work on similar topics.

**Comment by longxiang-ai** [comment]
Hi    @gjgjgjfff,

Thank you for your interest in our work! We're currently refining our codebase to ensure it's clean and well-structured. Our goal is to release a high-quality version that will be useful for academic and other purposes.

We don't have a specific release date yet, but we're working hard to make it available as soon as possible. We'll keep you updated once it's ready. Feel free to reach out if you have any more questions.

Best,
Mingwei Li
